api/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from users.models import User
from rest_framework import routers, serializers, viewsets

app_name = "api" 
 # 주문과 관련된 url 리스트
order_create = views.OrderAPIView.as_view({
    'post': 'create'
})

order_detail = views.OrderAPIView.as_view({
    'get': 'retrieve',
    'put': 'update_info',
    'delete': 'destroy'
})

order_payment = views.OrderAPIView.as_view({
    'get': 'get_payment'
})

orders = views.OrderAPIView.as_view({
    'get': 'get_orders'
})

current_orders = views.OrderAPIView.as_view({
    'get': 'get_current_order',
    'put': 'set_current_order'
})

user = views.UserViewSet.as_view({
    'get': 'get_session',
    'put': 'put_data'
})

payment = views.OrderAPIView.as_view({
    'get': 'verify_receipt',
    'delete': 'cancel_receipt'
})

urlpatterns = [
    url(r'^order/create$', order_create, name='api-order-create'),
    url(r'^user/session$', user, name='api-user-session'),
    url(r'^item/(?P<item_id>[0-9]+)/count', views.ItemAmountAdderAPIView.as_view(), name='api-item-count'),
    url(r'^user/(?P<user_id>[0-9]+)/current_order$', current_orders, name='api-get-user-current-orders'),
    url(r'^user/(?P<user_id>[0-9]+)/orders$', orders, name='api-get-user-orders'),
    url(r'^order/(?P<pk>[0-9]+)/payment/url$', order_payment, name='api-order-payment-url'),
    url(r'^order/(?P<pk>[0-9]+)/payment$', payment, name='api-order-payment'),
    url(r'^order/(?P<pk>[0-9]+)', order_detail, name='api-order-detail'),
    url(r'^oi/(?P<pk>[0-9]+)', views.OrderingItemView.as_view({'get': 'get', 'delete': 'delete', 'put':'put'}), name='api-oi')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ # 전체 url 리스트
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("qnas/", include("qnas.urls", namespace="qnas")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [ # 상품 관련된 url 리스트
    # path("",views.ItemByOuterView.as_view(), name="itembycategory"),
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_item, name="delete"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("admin/",views.AdminView.as_view(), name="admin-page"),
    path("categories/", views.CategoryView.as_view(), name="categories"),
    path("categories/add/", views.AddCategoryView.as_view(), name="add-category"),
    path("categories/<int:category_pk>/delete/", views.delete_category, name="delete-category"),
    path("categories/<int:category_pk>/edit/", views.EditCategoryView.as_view(), name="edit-category"),
    path("tags/", views.TagView.as_view(), name="tags"),
    path("tags/add/", views.AddTagView.as_view(), name="add-tag"),
    path("tags/<int:tag_pk>/delete/", views.delete_tag, name="delete-tag"),
    path("tags/<int:tag_pk>/edit/", views.EditTagView.as_view(), name="edit-tag"),
    path("<int:item_pk>/options/", views.OptionView.as_view(), name="options"),
    path("<int:item_pk>/options/add/", views.AddOptionView.as_view(), name="add-option"),
    path("options/<int:option_pk>/delete/", views.delete_option, name="delete-option"),
    path("options/<int:option_pk>/edit/", views.EditOptionView.as_view(), name="edit-option"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [ # users와 관련된 url 리스트에 대한 정의
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:item_pk>/", views.toggle_fav, name="toggle-favs"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("admin-profile/", views.AdminProfileView.as_view(), name="admin-profile"),
]

items/forms.py
from django import forms
from . import models

class CreateItemForm(forms.ModelForm): # 상품 등록 폼
    class Meta:
        model = models.Item
        fields=(
            "category",
            "name",
            "price",
            "count",
            "description",
        )
        
    def save(self, *args, **kwargs):
        item = super().save(commit=False)
        return item
    
class CreatePhotoForm(forms.ModelForm): # 상품 사진을 등록할 폼
    
    class Meta:
        model = models.Photo
        fields = (
            "file",
        )
        
    def save(self, pk, *args, **kwargs): # 사진 저장과 관련된 메소드
        photo = super().save(commit=False)
        item = models.Item.objects.get(pk=pk)
        photo.item = item
        photo.save()
        
class CreateCategoryForm(forms.ModelForm): # 상품 종류를 지정하는 뷰
    
    class Meta:
        model = models.Category
        fields = (
            "category_name",
        )    
    category_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "카테고리 이름을 입력해주세요"}))
    category_name.label = "카테고리명"
    
    def save(self, *args, **kwargs):
        category = super().save(commit=False)
        category.save()
        
class CreateTagForm(forms.ModelForm): # 상품 태그를 만드는 뷰
    
    class Meta:
        model = models.Tag
        fields = (
            "tag_name",
        )
    tag_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "태그 이름을 입력해주세요"}))
    tag_name.label = "태그명"
        
    def save(self, *args, **kwargs): # 태그 저장 메소드
        tag = super().save(commit=False)
        tag.save()

class CreateOptionForm(forms.ModelForm): # 상품 선택사항을 추가하는 폼
    
    class Meta:
        model = models.Option
        fields = (
            "name",
            "extra_money",
        )
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "옵션 이름을 입력해주세요"}))
    name.label = "옵션명"
    extra_money = forms.IntegerField()
    extra_money.label = "추가금"
        
    def save(self, item_pk, *args, **kwargs): # 상품 선택사항을 저장하는 메소드
        item = models.Item.objects.get(pk=item_pk)
        option = super().save(commit=False)
        option.item = item
        option.save()

items/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, FormView, UpdateView
from . import models, forms
from users import models as user_models

# Create your views here.
class HomeView(ListView): # 상품 리스트를 보여줄 뷰
    
    model = models.Item
    paginate_by = 12
    paginate_orphans = 5
    ordering = "-created"
    context_object_name = "items"
    
    def get_queryset(self):
        item_category = self.request.GET.get("category")
        search = self.request.GET.get("search")
        if item_category is not None:
            return models.Item.objects.filter(category__category_name=item_category).order_by("-created")
        if search is not None:
            return models.Item.objects.filter(name__icontains=search).order_by("-created")
        return models.Item.objects.all().order_by("-created")
    
class ItemDetail(DetailView): # 상품에 대한 상세 정보를 보여줄 뷰
    
    model = models.Item
    context_object_name = "item"
    
class CreateItemView(FormView): # 상품 생성과 관련된 뷰
    
    form_class = forms.CreateItemForm
    template_name = "items/item_create.html"
    
    def form_valid(self, form):
        item = form.save()
        item.owner = self.request.user
        item.save()
        form.save_m2m()
        return redirect(reverse("items:photos", kwargs={'pk': item.pk}))
    
class EditItemView(UpdateView): # 상품 정보 편집 뷰
    
    model = models.Item
    template_name = "items/item_edit.html"
    fields = (
            "category",
            "name",
            "price",
            "count",
            "description",
    )
    
    def get_success_url(self):
        item_pk = self.kwargs.get("pk")
        if self.request.GET.get("m") == "admin":
            return reverse("items:admin-page")
        return reverse("items:detail", kwargs={"pk":item_pk})
    
@login_required
def delete_item(request, pk): # 상품 삭제 뷰
    try:
        item = models.Item.objects.get(pk=pk)
        user = request.user
        if user == item.owner:
            item.delete()
            pass
        if request.GET.get("m") == "admin":
            return redirect(reverse("items:admin-page"))
        return redirect(reverse("core:home"))
    except models.Item.DoesNotExist:
        pass

class ItemPhotosView(DetailView): # 상품 사진과 관련된 뷰
    
    model = models.Item
    template_name = "items/photo/item_photos.html"
    
    def get_object(self, queryset=None):
        item = super().get_object(queryset=queryset)
        if not self.request.user.is_superuser:
            raise Http404()
        return item

class AddPhotoView(FormView): # 상품 이미지 추가 뷰
    
    template_name = "items/photo/photo_create.html"
    form_class = forms.CreatePhotoForm
    
    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        return redirect(reverse("items:photos", kwargs={'pk':pk}))
    
@login_required
def delete_photo(request, item_pk, photo_pk): # 상품 이미지 삭제 뷰
    user = request.user
    try:
        item = models.Item.objects.get(pk=item_pk)
        if item.owner.pk != user.pk:
            print("Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            print("Photo Deleted")
        return redirect(reverse("items:photos", kwargs={'pk':item_pk}))
    except models.Item.DoesNotExist:
        return redirect(reverse("core:home"))
    
class EditPhotoView(UpdateView): # 상품 이미지 편집과 관련된 뷰
    
    model = models.Photo
    template_name = "items/photo/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("file",)
    
    def get_success_url(self):
        item_pk = self.kwargs.get("item_pk")
        return reverse("items:photos", kwargs={"pk":item_pk})

# class ItemByOuterView(ListView):
#     paginate_by = 12
#     paginate_orphans = 5
#     ordering = "-created"
#     context_object_name = "items"
    
#     def get_queryset(self):
#         item_category = self.kwargs.get("category")
#         return models.Item.objects.filter(category__category_name=item_category)
    
class AdminView(ListView): # 관리자가 보는 상품 뷰
    
    model = models.Item
    template_name = "items/admin/item_admin.html"
    paginate_by = 5
    paginate_orphans = 2
    ordering = "-created"
    context_object_name = "items"
    
    def get_queryset(self):
        search = self.request.GET.get("search")
        if search is None:
            return models.Item.objects.all().order_by("-created")
        return models.Item.objects.filter(name__icontains=search).order_by("-created")
    
# 카테고리
class CategoryView(ListView): # 상품 종류 뷰
    model = models.Category
    template_name = "items/category/category_list.html"
    context_object_name = "categories"
    
    def get_object(self, queryset=None):
        category = super().get_object(queryset=queryset)
        return category

class AddCategoryView(FormView): # 상품 종류를 추가하는 뷰
    
    template_name = "items/category/category_create.html"
    form_class = forms.CreateCategoryForm
    
    def form_valid(self, form):
        form.save()
        return redirect(reverse("items:categories"))
    
@login_required
def delete_category(request, category_pk): # 상품 종류 삭제를 위한 뷰
    user = request.user
    try:
        category = models.Category.objects.get(pk=category_pk)
        if user.is_superuser:
            category.delete()
        return redirect(reverse("items:categories"))
    except models.Item.DoesNotExist:
        return redirect(reverse("core:home"))
    
class EditCategoryView(UpdateView): # 상품 종류 편집 뷰
    
    model = models.Category
    template_name = "items/category/category_edit.html"
    pk_url_kwarg = "category_pk"
    success_message = "Category_pk Updated"
    fields = (
        "category_name",
        )
    
    def get_success_url(self):
        category_pk = self.kwargs.get("category_pk")
        return reverse("items:categories")

# 태그
class TagView(ListView): # 태그를 보여줄 뷰
    model = models.Tag
    template_name = "items/tag/tag_list.html"
    context_object_name = "tags"
    
    def get_object(self, queryset=None):
        tag = super().get_object(queryset=queryset)
        return tag

class AddTagView(FormView): # 태그 추가를 위한 뷰
    
    template_name = "items/tag/tag_create.html"
    form_class = forms.CreateTagForm
    
    def form_valid(self, form):
        form.save()
        return redirect(reverse("items:tags"))
    
@login_required
def delete_tag(request, tag_pk): # 태그 삭제를 위한 메소드
    user = request.user
    try:
        tag = models.Tag.objects.get(pk=tag_pk)
        if user.is_superuser:
            tag.delete()
        return redirect(reverse("items:tags"))
    except models.Item.DoesNotExist:
        return redirect(reverse("core:home"))
    
class EditTagView(UpdateView): # 태그 퍈집을 위한 뷰
    
    model = models.Tag
    template_name = "items/tag/tag_edit.html"
    pk_url_kwarg = "tag_pk"
    success_message = "tag_pk Updated"
    fields = (
        "tag_name",
        )
    
    def get_success_url(self):
        tag_pk = self.kwargs.get("tag_pk")
        return reverse("items:tags")
    
# 옵션
class OptionView(ListView): # 상품 상세조건을 보여줄 뷰
    model = models.Option
    template_name = "items/option/option_list.html"
    context_object_name = "options"
    
    def get_queryset(self):
        item_pk = self.kwargs.get("item_pk")
        option = models.Item.objects.get(pk=item_pk).options.all()
        option.pk = item_pk
        if not self.request.user.is_superuser:
            raise Http404()
        return option

class AddOptionView(FormView): # 상세 조건 추가 뷰
    
    template_name = "items/option/option_create.html"
    form_class = forms.CreateOptionForm
    
    def form_valid(self, form):
        item_pk = self.kwargs.get("item_pk")
        form.save(item_pk)
        return redirect(reverse("items:options", kwargs={"item_pk":item_pk}))
    
@login_required
def delete_option(request, option_pk): # 상세 조건 삭제 뷰
    user = request.user
    try:
        option = models.Option.objects.get(pk=option_pk)
        if user.is_superuser:
            option.delete()
        return redirect(reverse("items:options", kwargs={"item_pk":option.item.pk}))
    except models.Item.DoesNotExist:
        return redirect(reverse("core:home"))
    
class EditOptionView(UpdateView): # 상세조건 편집 뷰
    
    model = models.Option
    template_name = "items/option/option_edit.html"
    pk_url_kwarg = "option_pk"
    success_message = "option_pk Updated"
    fields = (
        "name",
        "extra_money"
        )
    
    def get_object(self): 
        option_pk = self.kwargs.get("option_pk")
        option = models.Option.objects.get(pk=option_pk)
        return option
    
    def get_success_url(self):
        option_pk = self.kwargs.get("option_pk")
        option = models.Option.objects.get(pk=option_pk)
        return reverse("items:options", kwargs={"item_pk":option.item.pk})

templates/items/admin/item_admin.html
{% extends "base.html" %}

{% load humanize %}

{% block page_title %}
    상품 관리
{% endblock page_title %}
{% block content %}

    <div onload="admin_loac()" class="container mx-auto pb-10">
    <script>
        console.log("click");
        var search = document.getElementById('search');
        search.style.visibility="hidden";
    </script>

        <div class="flex">
            <div class="w-1/3 pl-3">
                <form method="GET" action="{% url 'items:admin-page' %}" class="w-9/12">
                    <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-full w-64 shadow-md hover:shadow-lg focus:outline-none" name="search" placeholder="Search" />
                </form>
            </div>
            <div class="w-1/3 font-semibold text-center text-2xl">상품 관리</div>
            <div class="w-1/3 flex justify-end">
                <a class="mr-5 ml-20 duration-500 px-6 py-2 border-gray-500 border-2 rounded-full mb-5 text-center font-bold hover:bg-gray-500 shadow-md hover:shadow-lg hover:text-white" href="{% url 'items:create' %}">상품 추가</a>
            </div>
        </div>

        {% comment %} item list {% endcomment %}
        <div class="border-t-2">
            {% for item in items  %}
                <div class="flex justify-between border-b-2 py-10 items-center w-full">
                    <div class="flex items-center">
                        <div class="text-2xl font-bold ml-5 text-center w-16">{{item.pk}}</div>
                        <a href="{% url 'items:detail' pk=item.pk %}">
                        <div class="w-32 h-32 bg-cover bg-center rounded-md ml-8" style="background-image:url({{item.thumbnail}})"></div>
                        </a>
                        <div class="ml-8">
                            <a href="{% url 'items:detail' pk=item.pk %}">
                                <p class="font-semibold text-xl mb-3 truncate">{{item.name}}</p>
                            </a>
                            <p class="font-semibold text-gray-600 mb-3">{{item.price|intcomma}}원</p>
                            <p class="font-semibold text-gray-600 mb-3">원재고량 : {{item.count}}개</p>
                            <p class="font-semibold text-gray-600 mb-3">출고량 : {{item.get_released}}개</p>
                            <p class="font-semibold text-gray-600 mb-3">남은물량 : {{item.get_remaining}}개</p>
                            <i class="fas fa-heart text-red-500 text-sm"></i>
                            <span class="fas text-red-500 text-sm">{{item.favs.count}}</span>
                        </div>
                    </div>
                    <div class="mb-4">
                    </div>
                    <div class="mr-5">
                            <input class="admin-item-count mb-2 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="admin_item_count_{{ item.pk }}" type="number" placeholder="추가할 재고량" data-id="{{ item.pk }}">
                            <a class="item-count-add-btn" data-id="{{ item.pk }}" data-input-id="admin_item_count_{{ item.pk }}" href="#">
                                <div class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-gray-600 shadow-md hover:shadow-lg hover:bg-gray-600 hover:text-white w-full mb-2">재고 추가</div>
                            </a>
                            <a href="{% url 'items:photos' item.pk %}">
                                <div class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-gray-600 shadow-md hover:shadow-lg hover:bg-gray-600 hover:text-white w-full mb-2">사진 편집</div>
                            </a>
                            <a href="{% url 'items:options' item_pk=item.pk %}">
                                <div class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-gray-600 shadow-md hover:shadow-lg hover:bg-gray-600 hover:text-white w-full mb-2">옵션 편집</div>
                            </a>
                            <a href="{% url 'items:edit' item.pk %}?m=admin">
                                <div class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-teal-400 shadow-md hover:shadow-lg hover:bg-teal-400 hover:text-white w-full mb-2">상품 편집</div>
                            </a>
                            <a href="{% url 'items:delete' item.pk %}?m=admin">
                                <div class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-red-400 shadow-md hover:shadow-lg hover:bg-red-400 hover:text-white w-full mb-2 ">상품 삭제</div>
                            </a>    
                    </div>
                </div>
            {% endfor %}
        </div>
        
        {% comment %} pagination {% endcomment %}
        {% if page_obj.paginator.num_pages != 1 %}
        <div class="flex items-center justify-center mx-auto container mt-5">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

            {% if page_obj.has_next  %}
                <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
        {% endif %}
        
        <div class="flex justify-center mt-8">
            <a href="{% url 'users:admin-profile' %}" class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-black text-black shadow-md hover:shadow-lg hover:bg-black hover:text-white">완료</a>
        </div>
    </div>
    
{% endblock content %}