api/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from users.models import User
from rest_framework import routers, serializers, viewsets

app_name = "api" 
 # 주문과 관련된 url 리스트
order_create = views.OrderAPIView.as_view({
    'post': 'create'
})

order_detail = views.OrderAPIView.as_view({
    'get': 'retrieve',
    'put': 'update_info',
    'delete': 'destroy'
})

order_payment = views.OrderAPIView.as_view({
    'get': 'get_payment'
})

orders = views.OrderAPIView.as_view({
    'get': 'get_orders'
})

current_orders = views.OrderAPIView.as_view({
    'get': 'get_current_order',
    'put': 'set_current_order'
})

user = views.UserViewSet.as_view({
    'get': 'get_session',
    'put': 'put_data'
})

payment = views.OrderAPIView.as_view({
    'get': 'verify_receipt',
    'delete': 'cancel_receipt'
})

urlpatterns = [
    url(r'^order/create$', order_create, name='api-order-create'),
    url(r'^user/session$', user, name='api-user-session'),
    url(r'^item/(?P<item_id>[0-9]+)/count', views.ItemAmountAdderAPIView.as_view(), name='api-item-count'),
    url(r'^user/(?P<user_id>[0-9]+)/current_order$', current_orders, name='api-get-user-current-orders'),
    url(r'^user/(?P<user_id>[0-9]+)/orders$', orders, name='api-get-user-orders'),
    url(r'^order/(?P<pk>[0-9]+)/payment/url$', order_payment, name='api-order-payment-url'),
    url(r'^order/(?P<pk>[0-9]+)/payment$', payment, name='api-order-payment'),
    url(r'^order/(?P<pk>[0-9]+)', order_detail, name='api-order-detail'),
    url(r'^oi/(?P<pk>[0-9]+)', views.OrderingItemView.as_view({'get': 'get', 'delete': 'delete', 'put':'put'}), name='api-oi')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ # 전체 url 리스트
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("qnas/", include("qnas.urls", namespace="qnas")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [ # 상품 관련된 url 리스트
    # path("",views.ItemByOuterView.as_view(), name="itembycategory"),
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_item, name="delete"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("admin/",views.AdminView.as_view(), name="admin-page"),
    path("categories/", views.CategoryView.as_view(), name="categories"),
    path("categories/add/", views.AddCategoryView.as_view(), name="add-category"),
    path("categories/<int:category_pk>/delete/", views.delete_category, name="delete-category"),
    path("categories/<int:category_pk>/edit/", views.EditCategoryView.as_view(), name="edit-category"),
    path("tags/", views.TagView.as_view(), name="tags"),
    path("tags/add/", views.AddTagView.as_view(), name="add-tag"),
    path("tags/<int:tag_pk>/delete/", views.delete_tag, name="delete-tag"),
    path("tags/<int:tag_pk>/edit/", views.EditTagView.as_view(), name="edit-tag"),
    path("<int:item_pk>/options/", views.OptionView.as_view(), name="options"),
    path("<int:item_pk>/options/add/", views.AddOptionView.as_view(), name="add-option"),
    path("options/<int:option_pk>/delete/", views.delete_option, name="delete-option"),
    path("options/<int:option_pk>/edit/", views.EditOptionView.as_view(), name="edit-option"),
]

templates/mixins/item_card.html
{% load humanize %}

<div class="w-1/4 mb-10 px-4 overflow-hidden">
    <a href="{% url 'items:detail' item.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{item.thumbnail}})"></div>
        <div>
            <span class="text-sm text-gray-600 block truncate mb-2">{{item.name}}</span>
            <div class="flex justify-between">
                <span class="text-black w-11/12 block truncate">{{item.price|intcomma}}원</span>
                <div class="flex">
                    <i class="fas fa-heart text-red-500 text-sm mr-1"></i>
                    <span class="fas text-red-500 text-sm mr-1">{{item.favs.count}}</span>
                </div>
            </div>
        </div>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
<div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover" style="background-image: url({{user.avatar.url}})">
{% else %}
<div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">
<span class="{{text|default:'text-2xl'}}">{{user.name|first}}</span>
{% endif %}
</div> 