api/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from users.models import User
from rest_framework import routers, serializers, viewsets

app_name = "api" 
 # 주문과 관련된 url 리스트
order_create = views.OrderAPIView.as_view({
    'post': 'create'
})

order_detail = views.OrderAPIView.as_view({
    'get': 'retrieve',
    'put': 'update_info',
    'delete': 'destroy'
})

order_payment = views.OrderAPIView.as_view({
    'get': 'get_payment'
})

orders = views.OrderAPIView.as_view({
    'get': 'get_orders'
})

current_orders = views.OrderAPIView.as_view({
    'get': 'get_current_order',
    'put': 'set_current_order'
})

user = views.UserViewSet.as_view({
    'get': 'get_session',
    'put': 'put_data'
})

payment = views.OrderAPIView.as_view({
    'get': 'verify_receipt',
    'delete': 'cancel_receipt'
})

urlpatterns = [
    url(r'^order/create$', order_create, name='api-order-create'),
    url(r'^user/session$', user, name='api-user-session'),
    url(r'^item/(?P<item_id>[0-9]+)/count', views.ItemAmountAdderAPIView.as_view(), name='api-item-count'),
    url(r'^user/(?P<user_id>[0-9]+)/current_order$', current_orders, name='api-get-user-current-orders'),
    url(r'^user/(?P<user_id>[0-9]+)/orders$', orders, name='api-get-user-orders'),
    url(r'^order/(?P<pk>[0-9]+)/payment/url$', order_payment, name='api-order-payment-url'),
    url(r'^order/(?P<pk>[0-9]+)/payment$', payment, name='api-order-payment'),
    url(r'^order/(?P<pk>[0-9]+)', order_detail, name='api-order-detail'),
    url(r'^oi/(?P<pk>[0-9]+)', views.OrderingItemView.as_view({'get': 'get', 'delete': 'delete', 'put':'put'}), name='api-oi')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ # 전체 url 리스트
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("qnas/", include("qnas.urls", namespace="qnas")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [ # 상품 관련된 url 리스트
    # path("",views.ItemByOuterView.as_view(), name="itembycategory"),
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.delete_item, name="delete"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("admin/",views.AdminView.as_view(), name="admin-page"),
    path("categories/", views.CategoryView.as_view(), name="categories"),
    path("categories/add/", views.AddCategoryView.as_view(), name="add-category"),
    path("categories/<int:category_pk>/delete/", views.delete_category, name="delete-category"),
    path("categories/<int:category_pk>/edit/", views.EditCategoryView.as_view(), name="edit-category"),
    path("tags/", views.TagView.as_view(), name="tags"),
    path("tags/add/", views.AddTagView.as_view(), name="add-tag"),
    path("tags/<int:tag_pk>/delete/", views.delete_tag, name="delete-tag"),
    path("tags/<int:tag_pk>/edit/", views.EditTagView.as_view(), name="edit-tag"),
    path("<int:item_pk>/options/", views.OptionView.as_view(), name="options"),
    path("<int:item_pk>/options/add/", views.AddOptionView.as_view(), name="add-option"),
    path("options/<int:option_pk>/delete/", views.delete_option, name="delete-option"),
    path("options/<int:option_pk>/edit/", views.EditOptionView.as_view(), name="edit-option"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [ # 리뷰와 관련된 url 리스트
    path("", views.ReviewView.as_view(), name="list"),
    path("form/<int:item_pk>/", views.CreateReview.as_view(), name="review-form"),
    path("<int:review_pk>/delete/", views.delete_review, name="delete"),
    path("<int:review_pk>/edit/", views.EditReviewView.as_view(), name="edit"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [ # users와 관련된 url 리스트에 대한 정의
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:item_pk>/", views.toggle_fav, name="toggle-favs"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("admin-profile/", views.AdminProfileView.as_view(), name="admin-profile"),
]

reviews/models.py
from django.db import models
from core import models as core_models

# Create your models here.
class Review(core_models.TimeStampedModel): # 리뷰에 대한 모델을 정의한 클래스
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey("users.User", related_name="reviews", on_delete=models.CASCADE)
    item = models.ForeignKey("items.Item", related_name="reviews", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
    
    def get_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None
        
# class Photo(models.Model):
#     file = models.ImageField(upload_to="review_photos")
#     review = models.ForeignKey("Review",related_name="photos" , on_delete=models.CASCADE, null = True, blank=True)
    
# class Recomment(core_models.TimeStampedModel):
#     title = models.CharField(max_length=50)
#     content = models.TextField()
#     user = models.ForeignKey("users.User", related_name="recomments", on_delete=models.CASCADE)
#     review = models.ForeignKey("Review", related_name="recomments", on_delete=models.CASCADE)
    
#     def __str__(self):
#         return self.title
    

reviews/forms.py
from django import forms
from . import models
from items import models as item_models

class CreateReviewForm(forms.ModelForm): # 리뷰 생성에 관한 폼을 정의한 메소드
    class Meta:
        model = models.Review
        fields=(
            "title",
            "content",
        )
        
    def save(self, item_pk): # 리뷰 저장 메소드
        review = super().save(commit=False)
        item = item_models.Item.objects.get(pk=item_pk)
        review.item = item
        return review

reviews/views.py
from django.http import Http404 
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, UpdateView, ListView
from items import models as item_models
from . import forms, models

# Create your views here.
def create_review(request, item_pk): # 리뷰생성에 관한 메소드
    title = request.POST['title']
    content = request.POST['content']
    if title != "" and content != "":
        item = item_models.Item.objects.get(pk=item_pk)
        user = request.user
        
        review = models.Review.objects.create(
            item = item,
            user = user,
            title = title,
            content = content,
        )
        review.save()
        return redirect(reverse("items:detail", kwargs={"pk":item.pk}))
    else:
        return redirect(reverse("core:home"))
    
class CreateReview(FormView):  # 리뷰 생성과 관련된 클래스
    form_class = forms.CreateReviewForm
    template_name = "reviews/review_form.html"
    
    def form_valid(self, form):
        pk = self.kwargs.get('item_pk')
        review = form.save(pk)
        review.user = self.request.user
        review.save()
        return redirect(reverse("items:detail", kwargs={'pk': pk}))

@login_required
def delete_review(request, review_pk): #리뷰 삭제에 대한 메소드
    try:
        review = models.Review.objects.get(pk=review_pk)
        item_pk = review.item.pk
        user = request.user
        if user == review.user or user.is_superuser:
            review.delete()
            pass
        if request.GET.get("m") == "admin":
            return redirect(reverse("reviews:list"))
        return redirect(reverse("items:detail", kwargs={"pk":item_pk}))
    except models.Review.DoesNotExist:
        pass
    
class EditReviewView(UpdateView): # 리뷰 편집에 관한 클래스
    
    model = models.Review
    template_name = "reviews/review_edit.html"
    pk_url_kwarg = "review_pk"
    success_message = "review Updated"
    fields = (
        "title",
        "content",
        )
    
    def get_object(self): # 편집된 리뷰를 반환하는 메소드
        review_pk = self.kwargs.get("review_pk")
        review = models.Review.objects.get(pk=review_pk)
        return review
    
    def get_success_url(self): # 성공적으로 변환시키고 페이지를 반환하는 메소드
        review_pk = self.kwargs.get("review_pk")
        review = models.Review.objects.get(pk=review_pk)
        return reverse("items:detail", kwargs={"pk":review.item.pk})
    
class ReviewView(ListView): # 리뷰를 나타낼 클래스 정의
    model = models.Review.objects.all()
    template_name = "reviews/review_list.html"
    context_object_name = "reviews"
    
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created"
    
    def get_queryset(self): # 리뷰 리스트를 반환하는 메소드
        search = self.request.GET.get("search")
        if search is not None:
            review = models.Review.objects.filter(Q(title__icontains=search)|Q(content__icontains=search)|Q(user__name__icontains=search)|Q(item__name__icontains=search)).order_by("-created")
        else:
            review = models.Review.objects.all().order_by("-created")
        if not self.request.user.is_superuser:
            raise Http404()
        return review
    
# def create_order(request, item_pk):
#     user = request.user
#     option_pk = request.POST['option']
      
#     try:
#         item = item_models.Item.objects.get(pk=item_pk)
#         option = item_models.Option.objects.get(pk=option_pk)
#         price = (item.price + option.extra_money)
#         order = models.OrderList.objects.create(
#             item=item,
#             option=option,
#             user=user,
#             price=price,
#         )
#         order.save()
#         return redirect(reverse("core:home"))
#     except models.OrderList.DoesNotExist:
#         return redirect(reverse("core:home"))

templates/reviews/review_edit.html
{% extends 'base.html' %}

{% block page_title %}
    리뷰 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto rounded-md my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/item/item_form.html' with form=form cta="리뷰 수정" %}

    </div>
{% endblock content %}

templates/reviews/review_form.html
{% extends 'base.html' %}

{% block page_title %}
    리뷰 작성
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400 rounded-md">
            {% include 'mixins/item/item_form.html' with form=form cta="리뷰 작성" %}
    </div>

{% endblock content %}

templates/reviews/review_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block page_title %}
    리뷰 관리
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container w-1/2 mx-auto">

        <div class="flex items-center mb-5">
            <div class="w-1/3 pl-3">
                <form method="GET" action="{% url 'reviews:list' %}" class="w-9/12">
                    <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-full w-64 shadow-md hover:shadow-lg focus:outline-none" name="search" placeholder="Search" />
                </form>
            </div>
            <div class="w-1/3 font-semibold text-center text-2xl">리뷰 관리</div>
            <div class="w-1/3">
            </div>
        </div>

        {% comment %} Review List {% endcomment %}
        <div class="border-t-2">
            {% for review in reviews  %}
            <div class="border-section my-5 border-b-2">
                <div class="ml-5 mb-1 flex">

                    <div class="flex items-center">
                        <a href="{% url 'items:detail' pk=review.item.pk %}" class="w-16">
                            <div class="w-16 h-16 bg-cover bg-center rounded-md" style="background-image:url({{review.item.thumbnail}})"></div>
                            <div class="font-semibold text-xs mb-3 truncate">{{review.item.name}}</div>
                        </a>
                    </div>

                    <div class="text-center ml-5">
                        {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-lg' %}
                        <span class="text-xs text-gray-500">{{review.user.name}}</span>
                    </div>
                    <div class="flex flex-col ml-5">
                        <div>
                            <span class="font-medium font-bold">{{review.title}}</span>
                            <span class="ml-1 text-xs text-gray-500">{{review.created|date:'F Y'}}</span>
                            {% if user.is_superuser %}
                            <a href="{% url 'reviews:delete' review_pk=review.pk %}?m=admin" class="duration-500 ml-1 text-sm text-red-500 font-semibold hover:text-red-700">삭제</a>
                            {% endif %}
                        </div>
                        <p class="text-gray-600 text-sm">{{review.content}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% comment %} pagination {% endcomment %}
        {% if page_obj.paginator.num_pages != 1 %}
        <div class="flex items-center justify-center mx-auto container mt-5">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

            {% if page_obj.has_next  %}
                <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
        {% endif %}

        <div class="flex justify-center mt-8">
            <a href="{% url 'users:admin-profile' %}" class="duration-500 rounded-full px-6 py-2 text-center font-semibold border-2 border-black text-black shadow-md hover:shadow-lg hover:bg-black hover:text-white">완료</a>
        </div>
    </div>
{% endblock content %}