api/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from users.models import User
from rest_framework import routers, serializers, viewsets

app_name = "api" 
 # 주문과 관련된 url 리스트
order_create = views.OrderAPIView.as_view({
    'post': 'create'
})

order_detail = views.OrderAPIView.as_view({
    'get': 'retrieve',
    'put': 'update_info',
    'delete': 'destroy'
})

order_payment = views.OrderAPIView.as_view({
    'get': 'get_payment'
})

orders = views.OrderAPIView.as_view({
    'get': 'get_orders'
})

current_orders = views.OrderAPIView.as_view({
    'get': 'get_current_order',
    'put': 'set_current_order'
})

user = views.UserViewSet.as_view({
    'get': 'get_session',
    'put': 'put_data'
})

payment = views.OrderAPIView.as_view({
    'get': 'verify_receipt',
    'delete': 'cancel_receipt'
})

urlpatterns = [
    url(r'^order/create$', order_create, name='api-order-create'),
    url(r'^user/session$', user, name='api-user-session'),
    url(r'^item/(?P<item_id>[0-9]+)/count', views.ItemAmountAdderAPIView.as_view(), name='api-item-count'),
    url(r'^user/(?P<user_id>[0-9]+)/current_order$', current_orders, name='api-get-user-current-orders'),
    url(r'^user/(?P<user_id>[0-9]+)/orders$', orders, name='api-get-user-orders'),
    url(r'^order/(?P<pk>[0-9]+)/payment/url$', order_payment, name='api-order-payment-url'),
    url(r'^order/(?P<pk>[0-9]+)/payment$', payment, name='api-order-payment'),
    url(r'^order/(?P<pk>[0-9]+)', order_detail, name='api-order-detail'),
    url(r'^oi/(?P<pk>[0-9]+)', views.OrderingItemView.as_view({'get': 'get', 'delete': 'delete', 'put':'put'}), name='api-oi')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ # 전체 url 리스트
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("qnas/", include("qnas.urls", namespace="qnas")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [ # 주문과 관련된 url 정의 리스트
    path('', views.OrderList.as_view(), name="all"),
    path('complete/', views.order_pay_complete_notify.as_view(), name="complete"),
    path('cancel/', views.order_cancel_notify.as_view(), name="cancel"),
    path('error/', views.order_error_notify.as_view(), name="error"),
    path("<int:pk>/", views.OrderDetail.as_view(), name="detail"),
    path("<int:order_id>/callback/", views.order_callback, name="callback"),
    path("<int:order_pk>/delete/", views.delete_order, name="delete-order"),
    path("<int:order_pk>/pay/cancel/", views.delete_order, name="cancel-pay"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [ # users와 관련된 url 리스트에 대한 정의
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:item_pk>/", views.toggle_fav, name="toggle-favs"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("admin-profile/", views.AdminProfileView.as_view(), name="admin-profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from phone_field import PhoneField
from django.shortcuts import reverse
from django.db import models
from core import models as core_models
from orders.models import Order

# Create your models here.


class User(AbstractUser): # 유저 모델에 대한 정의
    # 성별에 대한 정의
    GENDER_MALE = "male"
    GENDER_FEMALE = "female"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
    )

    # 필드들에 대한 정의
    name = models.CharField(max_length=10) # 이름
    gender = models.CharField(choices=GENDER_CHOICES, # 성별
                              max_length=10, blank=True)
    address1 = models.CharField(max_length=1024) # 주소
    address2 = models.CharField(max_length=1024) # 상세주소
    postal_code = models.CharField(max_length=7, blank=True) # 우편 번호
    birthdate = models.DateField(null=True) # 생일

    email_confirmed = models.BooleanField(default=False) # 이메일 인증을 받았는지 여부
    email_secret = models.CharField(max_length=20, default="", blank=True) # 이메일

    home_number = PhoneField(blank=True, help_text='Contact home number') # 집 전화 번호
    phone_number = PhoneField(blank=True, help_text='Contact phone number') # 전화 번호

    current_order = models.ForeignKey("orders.Order", related_name="users", on_delete=models.SET_NULL, blank=True, null=True) # 현재 주문
    favlist = models.ManyToManyField("items.Item", related_name="favs" , blank=True) # 관심 목록
    
    def get_absolute_url(self): # 유저 정보에 대한 요청시 처리할 메소드
        return reverse("users:profile")
    
    def get_total_order_price(self): # 전체 주문에 대한 가격 반환할 메소드
        total = 0
        for order in self.orders.all():
            total += order.GetActualPrice()
        return total
    
    def get_total_order_count(self): # 전체 주문의 갯수를 반환할 메소드
        return self.orders.all().count()
    
    def get_pay_confirmed(self): # 모든 주문에 대해 완료 할 메소드
        count = 0
        for order in self.orders.all():
            if order.state == "pay_confirmed":
                count += 1
        return count
    
    def get_on_delivery(self): # 주문에 맞게 배달 중이라고 알릴 메소드
        count = 0
        for order in self.orders.all():
            if order.state == "on_delivery":
                count += 1
        return count

    def get_wait_submit(self): # 주문확인에 대한 메소드
        count = 0
        for order in self.orders.all():
            if order.state == "wait_submit":
                count += 1
        return count
    
    def get_ended_delivery(self): # 배달 완료에 대한 메소드
        count = 0
        for order in self.orders.all():
            if order.state == "ended_delivery":
                count += 1
        return count
    
    def get_pay_canceled(self): # 결제 취소에 대한 메소드
        count = 0
        for order in self.orders.all():
            if order.state == "pay_canceled":
                count += 1
        return count

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models


class LoginForm(forms.Form): # 로그인 폼

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={"placeholder": "Email"})) # 이메일
    
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}) # 비밀 번호
    )
    email.label="이메일"
    password.label="비밀번호"

    def clean(self): # 지워진 데이터
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError(
                "User does not exist"))


class SignUpForm(forms.ModelForm): # 회원 가입 폼
    class Meta:
        model = models.User # 유저 모델 그대로 사용해서 포함
        fields = ( # 사용할 필드
            "email",
            "name",
            "birthdate",
        )
        widgets = { # 사용할 위젯
            "email": forms.EmailInput(attrs={"placeholder": "이메일 주소를 입력하세요"}),
            "name": forms.TextInput(attrs={"placeholder": "이름을 입력하세요"}),
            "birthdate": forms.DateTimeInput(attrs={"placeholder": "YY-MM-DD"}),
        }
        
        # 입력창
    email = forms.CharField(widget=forms.EmailInput(attrs={"placeholder": "이메일 주소를 입력하세요"})) 
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "이름을 입력하세요"}))
    birthdate = forms.DateField(widget=forms.DateTimeInput(attrs={"placeholder": "YY-MM-DD"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))
    
    email.label = "이메일"
    name.label = "이름"
    birthdate.label = "생년월일"
    password.label = "비밀번호"
    password1.label = "비밀번호 확인"

    def clean_password1(self): # 비밀번호 검사 후 다르면 지우고 에러 출력하는 메소드
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("비밀번호를 확인해주세요.")
        else:
            return password

    def save(self, *args, **kwrgs): # 저장 하는 메소드
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.clean_password1()
        name = self.cleaned_data.get("name")
        # name = self.get("name")
        user.name = name
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, TemplateView, UpdateView
from django.urls import reverse_lazy
from . import forms, models, mixins
from items import models as item_models
            
class LoginView(mixins.LoggedOutOnlyView, FormView): # 로그인 뷰

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form): # 로그인 정보가 확실한지 확인 할 메소드
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self): # 성공적으로 로그인 했을때 메소드
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request): # 로그아웃 메소드
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView): # 회원가입 창을 나타낸 메소드
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("users:update")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        if user is not None:
            login(self.request, user)

        return super().form_valid(form)

def toggle_fav(request, item_pk): # 관심 목록에서 빼거나 추가하는 메소드
    action = request.GET.get("action", None)
    item = item_models.Item.objects.get_or_none(pk=item_pk)
    user = request.user
    if item is not None and action is not None:
        if action == "add":
            user.favlist.add(item)
        else:
            user.favlist.remove(item)
    return redirect(reverse("items:detail", kwargs={"pk":item_pk}))
    
class SeeFavsView(mixins.LoggedInOnlyView, TemplateView): # 관심 목록을 보여주는 메소드
    template_name = "users/fav/favlist_list.html"
    
class UserProfileView(mixins.LoggedInOnlyView, TemplateView): # 유저 정보를 보여주는 메소드
    template_name = "users/user_detail.html"
    
class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView): # 유저 정보를 갱신하는 메소드
    
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "name",
        "gender",
        "address1",
        "address2",
        "postal_code",
        "birthdate",
        "home_number",
        "phone_number",
    )
    
    def get_object(self, queryset=None): # 유저 자체 반환 메소드
        return self.request.user
    
    def get_form(self, form_class=None): # 유저 정보를 보여주는 메소드
        form = super().get_form(form_class=form_class)
        form.fields['name'].widget.attrs= {"placeholder": "Name"}
        form.fields['gender'].widget.attrs= {"placeholder": "Gender"}
        form.fields['address1'].widget.attrs= {"placeholder": "Address1"}
        form.fields['address2'].widget.attrs= {"placeholder": "Address2"}
        form.fields['postal_code'].widget.attrs= {"placeholder": "Postal Code"}
        form.fields['birthdate'].widget.attrs= {"placeholder": "Birthdate"}
        form.fields['home_number'].widget.attrs= {"placeholder": "Home Number"}
        form.fields['phone_number'].widget.attrs= {"placeholder": "Phone Number"}
        form.fields["name"].label = "이름"
        form.fields["gender"].label = "성별"
        form.fields["address1"].label = "주소1"
        form.fields["address2"].label = "주소2"
        form.fields["postal_code"].label = "우편번호"
        form.fields["birthdate"].label = "생년월일"
        form.fields["home_number"].label = "집전화"
        form.fields["phone_number"].label = "휴대전화"
        return form
    
class UpdatePasswordView(mixins.LoggedInOnlyView, PasswordChangeView): # 비밀번호 변경 메소드
    
    template_name = "users/update-password.html"
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['old_password'].widget.attrs= {"placeholder": "Current password"}
        form.fields['new_password1'].widget.attrs= {"placeholder": "New password"}
        form.fields['new_password2'].widget.attrs= {"placeholder": "Confirm new password"}
        form.fields['old_password'].label = "현재 암호"
        form.fields['new_password1'].label = "새로운 암호"
        form.fields['new_password2'].label = "새로운 암호 확인"
        return form
    
    def get_success_url(self):
        return self.request.user.get_absolute_url()
    
class AdminProfileView(mixins.LoggedInOnlyView, TemplateView): # 관리자 정보를 보여주는 폼을 정의한 메소드
    
    template_name = "users/admin/admin-profile.html"

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}
    Login
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center rounded-md border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="로그인" %}
        <div class="mt-5">
            <span class="mr-2">계정 없으신가요?</span>
            <a href="{% url 'users:signup' %}" class="duration-500 text-teal-500 hover:text-teal-800">회원가입</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}


{% block page_title %}
회원가입
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}


{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center rounded-md border p-6 border-gray-400">
    {% include 'mixins/auth/auth_form.html' with form=form cta="회원가입" %}
    <div class="mt-5">
        <span class="mr-2">이미 계정이 있으신가요?</span>
        <a href="{% url 'users:login' %}" class="duration-500 text-teal-500 hover:text-teal-800">로그인</a>
    </div>
</div>

{% endblock content %}

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}
    암호 변경
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="min-h-75vh">
    <div class="container rounded-md lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="암호 변경" %}
    </div>
</div>
{% endblock content %}

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_title %}
    회원정보 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 rounded-md mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="프로필 수정" %}  
        <div class="mt-5">
            <a href={% url 'users:password' %} class="duration-500 text-teal-500 font-medium hover:text-teal-800">암호 변경</a>
        </div>
    </div>

{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block page_title %}
    {{user.name}}님의 정보
{% endblock page_title %}

{% block content %}

    <div class="min-h-75vh">
        <p class="font-semibold text-center text-2xl">내 정보</p>

        <div class="mx-auto w-2/3">
            <div class="flex border border-gray-400 px-5 py-5 items-center my-6">
                {% include "mixins/user_avatar.html" with user=user %}
                <span class="ml-5">저희 쇼핑몰을 이용해 주셔서 감사합니다.</span>
            </div>
            
            <div class="flex border-8 mb-6">
                <div class="border-r w-1/2 px-10 py-6 text-sm">
                    <div class="flex justify-between mb-3">
                        <div>
                            <span class="font-bold">></span>
                            <span>가용적립금</span>
                        </div>
                        <span>0원</span>
                    </div>
                    <div class="flex justify-between">
                        <div>
                            <span class="font-bold">></span>
                            <span>사용적립금</span>
                        </div>
                        <span>0원</span>
                    </div>

                </div>

                <div class="w-1/2 px-10 py-6 text-sm">
                    <div class="flex justify-between mb-3">
                        <div>
                            <span class="font-bold">></span>
                            <span>총적립금</span>
                        </div>
                        <span>0원</span>
                    </div>
                    <div class="flex justify-between">
                        <div>
                            <span class="font-bold">></span>
                            <span>총주문</span>
                        </div>
                        <span>{{user.get_total_order_price|intcomma}}원({{user.get_total_order_count}}개)</span>
                    </div>
                </div>
            </div>

            <div class="border w-full mb-6">
                <div class="bg-gray-200 font-semibold px-6 py-2 border-b">나의 주문처리 현황</div>

                <div class="flex justify-between my-5">
                    <div class="border-r border-dotted px-5 py-5 w-1/5 text-center">
                        <p class="font-semibold">결제전</p>
                        <p class="font-semibold text-2xl">{{user.get_pay_confirmed}}</p>
                    </div>

                    <div class="border-r border-dotted px-5 py-5 w-1/5 text-center">
                        <p class="font-semibold">배송준비중</p>
                        <p class="font-semibold text-2xl">{{user.get_wait_submit}}</p>
                    </div>

                    <div class="border-r border-dotted px-5 py-5 w-1/5 text-center">
                        <p class="font-semibold">배송중</p>
                        <p class="font-semibold text-2xl">{{user.get_on_delivery}}</p>
                    </div>

                    <div class="border-r border-dotted px-5 py-5 w-1/5 text-center">
                        <p class="font-semibold">배송완료</p>
                        <p class="font-semibold text-2xl">{{user.get_ended_delivery}}</p>
                    </div>

                    <div class="px-5 py-5 w-1/5 text-center text-sm">
                        <div>
                            <span>· 취소 : </span>
                            <span class="text-sm font-semibold ml-2">{{user.get_pay_canceled}}</span>
                        </div>
                        <div>
                            <span>· 교환 : </span>
                            <span class="font-semibold ml-2">0</span>
                        </div>
                        <div>
                            <span>· 반품 : </span>
                            <span class="font-semibold ml-2">0</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="w-full flex justify-between">
                <a href="{% url 'orders:all' %}" class="duration-500 border w-1/3 text-center rounded-sm hover:border-black py-5">
                    <p class="text-2xl font-bold mb-2">ORDER</p>
                    <p class="text-gray-600 text-sm mb-4">주문내역 조회</p>
                </a>

                <a href="{% url 'users:update' %}" class="duration-500 border w-1/3 mx-3 text-center rounded-sm hover:border-black py-5">
                    <p class="text-2xl font-bold mb-2">PROFILE</p>
                    <p class="text-gray-600 text-sm mb-4">회원 정보 수정</p>
                </a>

                <a href="{% url 'users:see-favs' %}" class="duration-500 border w-1/3 text-center rounded-sm hover:border-black py-5">
                    <p class="text-2xl font-bold mb-2">WISHLIST</p>
                    <p class="text-gray-600 text-sm mb-4">관심 상품</p>
                </a>
            </div>

    </div>

{% endblock content %}